import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';

import type { Metadata } from 'next';

import Header from '@/components/Header/Header';

import { getUser } from '@/shared/lib/auth0/getUser';
import AppProviders from '@/shared/providers/AppProvider';

import './globals.css';

export const metadata: Metadata = {
  title: 'Booking CRM',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userWithToken = await getUser();
  const { user = null, accessToken = null } = userWithToken ?? {};
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute="class" />
        <AppProviders accessToken={accessToken} user={user}>
          <Header />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
