import { Tour } from '@/entities/tour';

export const mockTour: Tour = {
  id: 1,
  operatorId: 18,
  title: 'Романтична Флоренція',
  description:
    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla nostrum reiciendis animi\n            incidunt amet fugit at voluptatibus, id dolor dolorem suscipit quos reprehenderit dicta ipsam magni\n            asperiores voluptatum repellendus labore.',
  countryISO2Code: 'FR',
  cityId: 1,
  price: '78 567',
  currency: 'EUR',
  startDate: '2025-10-01',
  endDate: '2025-10-07',
  availableSpots: 2,
  isActive: true,
  adults: 1,
  children: 0,
  petsAllowed: false,
  departureCityId: null,
  departureCountryISO2Code: null,
  createdAt: '2025-09-29T12:02:12.599Z',
  updatedAt: '2025-09-29T12:02:12.599Z',
  photos: [
    {
      id: 1,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: true,
      description: 'Main photo',
    },
    {
      id: 2,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: false,
      description: 'secondary photo',
    },
    {
      id: 3,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: false,
      description: 'secondary photo',
    },
    {
      id: 4,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: false,
      description: 'secondary photo',
    },
    {
      id: 5,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: false,
      description: 'secondary photo',
    },
    {
      id: 6,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: false,
      description: 'secondary photo',
    },
    {
      id: 7,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: false,
      description: 'secondary photo',
    },
  ],
  operator: {
    id: 18,
    email: 'volodymyrquo@gmail.com',
    createdAt: '2025-09-25T07:06:43.115Z',
    updatedAt: '2025-09-25T07:06:43.115Z',
    userId: 186,
    companyName: 'Приватна особа',
    description: 'Приватна особа оператор турів',
    firstName: 'Олена',
    lastName: 'Петренко',
    website: 'https://instagram.com',
    phone: '+380671111111',
    status: 'approved',
    philosophy: null,
    photo: null,
  },
  country: {
    id: 73,
    iso2: 'FR',
    iso3: 'FRA',
    translations: [
      {
        id: 41,
        countryIso2: 'FR',
        languageCode: 'en',
        name: 'Італія',
      },
    ],
  },
  city: {
    id: 1,
    countryIso2: 'FR',
    translations: [
      {
        id: 1,
        cityId: 1,
        languageCode: 'en',
        name: 'Флоренція',
      },
    ],
  },
  departureCity: null,
  type: null,
  conditions: null,
};

export const mockCardProps = {
  id: 1,
  title: 'Романтична Флоренція',
  availableSpots: 12,
  price: '78 567',
  startDate: '2025-10-02',
  endDate: '2025-10-03',
  countryName: 'Італія',
  photos: [
    {
      id: 85,
      tourId: 74,
      url: '/images/tourCard/tour.png',
      isMain: true,
      description: 'Main photo',
    },
    {
      id: 86,
      tourId: 74,
      url: 'https://res.cloudinary.com/dqcjjscle/image/upload/v1759147329/uploads/nuhdk2gkqbbomubfoch1.jpg',
      isMain: false,
      description: 'secondary photo',
    },
  ],
  operator: {
    firstName: 'Олена',
    lastName: 'Петренко',
    photo: null,
  },
};
